export interface Country {
    code: string;
    label: string;
}

export const COUNTRIES: Country[] = [
    { code: "xa-ar", label: "Arabia (ar)" },
    { code: "xa-en", label: "Arabia (en)" },
    { code: "ar-es", label: "Argentina" },
    { code: "au-en", label: "Australia" },
    { code: "at-de", label: "Austria" },
    { code: "be-fr", label: "Belgium (fr)" },
    { code: "be-nl", label: "Belgium (nl)" },
    { code: "br-pt", label: "Brazil" },
    { code: "bg-bg", label: "Bulgaria" },
    { code: "ca-en", label: "Canada (en)" },
    { code: "ca-fr", label: "Canada (fr)" },
    { code: "ct-ca", label: "Catalan" },
    { code: "cl-es", label: "Chile" },
    { code: "cn-zh", label: "China" },
    { code: "co-es", label: "Colombia" },
    { code: "hr-hr", label: "Croatia" },
    { code: "cz-cs", label: "Czech Republic" },
    { code: "dk-da", label: "Denmark" },
    { code: "ee-et", label: "Estonia" },
    { code: "fi-fi", label: "Finland" },
    { code: "fr-fr", label: "France" },
    { code: "de-de", label: "Germany" },
    { code: "gr-el", label: "Greece" },
    { code: "hk-tzh", label: "Hong Kong" },
    { code: "hu-hu", label: "Hungary" },
    { code: "in-en", label: "India (en)" },
    { code: "id-id", label: "Indonesia (id)" },
    { code: "id-en", label: "Indonesia (en)" },
    { code: "ie-en", label: "Ireland" },
    { code: "il-he", label: "Israel" },
    { code: "it-it", label: "Italy" },
    { code: "jp-jp", label: "Japan" },
    { code: "kr-kr", label: "Korea" },
    { code: "lv-lv", label: "Latvia" },
    { code: "lt-lt", label: "Lithuania" },
    { code: "xl-es", label: "Latin America" },
    { code: "my-ms", label: "Malaysia (ms)" },
    { code: "my-en", label: "Malaysia (en)" },
    { code: "mx-es", label: "Mexico" },
    { code: "nl-nl", label: "Netherlands" },
    { code: "nz-en", label: "New Zealand" },
    { code: "no-no", label: "Norway" },
    { code: "pe-es", label: "Peru" },
    { code: "ph-en", label: "Philippines (en)" },
    { code: "ph-tl", label: "Philippines (tl)" },
    { code: "pl-pl", label: "Poland" },
    { code: "pt-pt", label: "Portugal" },
    { code: "ro-ro", label: "Romania" },
    { code: "ru-ru", label: "Russia" },
    { code: "sg-en", label: "Singapore" },
    { code: "sk-sk", label: "Slovak Republic" },
    { code: "sl-sl", label: "Slovenia" },
    { code: "za-en", label: "South Africa" },
    { code: "es-es", label: "Spain" },
    { code: "se-sv", label: "Sweden" },
    { code: "ch-de", label: "Switzerland (de)" },
    { code: "ch-fr", label: "Switzerland (fr)" },
    { code: "ch-it", label: "Switzerland (it)" },
    { code: "tw-tzh", label: "Taiwan" },
    { code: "th-th", label: "Thailand" },
    { code: "tr-tr", label: "Turkey" },
    { code: "ua-uk", label: "Ukraine" },
    { code: "uk-en", label: "United Kingdom" },
    { code: "us-en", label: "United States (en)" },
    { code: "ue-es", label: "United States (es)" },
    { code: "ve-es", label: "Venezuela" },
    { code: "vn-vi", label: "Vietnam" },
    { code: "wt-wt", label: "No region" },
];
